ehn: add support for doc verification
smileidentity/smile-identity-core-php pull request #5
Opened 2022-01-28 17:32 UTC by macphilips

2022-01-31 15:59 UTC, ArlonTM approved these changes
Everything looks fine. Two observations/questions:

- Does this include the migration to the new endpoint?
- Could you update the tests with new cases to reflect the document verification work?

2022-02-07 18:02 UTC, beaglebets requested changes
Please add some tests that these changes work as expected.

2022-02-14 19:10 UTC, ArlonTM approved these changes
All scenarios covered!👍🏽👌🏽

2022-02-15 14:17 UTC, tamssokari approved these changes

2022-02-15 15:08 UTC, merged